" Name:         Vanilla Cake
" Description:  🍰 Light & Eye-friendly Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-vanilla-cake/
" License:      MIT && Anti-996
" Last Updated: Sun 14 Jul 2019 09:00:39 PM CST

" Generated by Colortemplate v2.0.0rc1

set background=light

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'vanilla-cake'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link SpecialChar Special
hi! link Debug Special
hi! link Include PreProc
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#566b60', '#d4576a', '#2d8d4c', '#cc8500',
        \ '#5c7aa9', '#c56591', '#36817e', '#f9ebd0', '#566b60', '#d4576a',
        \ '#2d8d4c', '#cc8500', '#5c7aa9', '#c56591', '#36817e', '#f9ebd0']
  if get(g:, 'light_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#566b60 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#566b60 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#566b60 guibg=#f9ebd0 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#566b60 guibg=#f9ebd0 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#f9ebd0 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#566b60 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#778b81 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#c1e5b1 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#bae1f0 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#f6babd guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#eecbb4 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#36817e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#778b81 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#778b81 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#c1e5b1 guisp=NONE gui=underline cterm=underline
  hi Search guifg=NONE guibg=#c1e5b1 guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#566b60 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#f9ebd0 guibg=#778b81 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#778b81 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#d4576a guibg=NONE guisp=#d4576a gui=NONE cterm=NONE
  hi SpellCap guifg=#d26e41 guibg=NONE guisp=#d26e41 gui=NONE cterm=NONE
  hi SpellLocal guifg=#5c7aa9 guibg=NONE guisp=#5c7aa9 gui=NONE cterm=NONE
  hi SpellRare guifg=#c56591 guibg=NONE guisp=#c56591 gui=NONE cterm=NONE
  hi StatusLine guifg=#f9ebd0 guibg=#778b81 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#566b60 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#566b60 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#566b60 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#f9ebd0 guibg=#778b81 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#f6e2ba guisp=NONE gui=italic cterm=italic
  hi WildMenu guifg=#f9ebd0 guibg=#566b60 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#c56591 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conditional guifg=#c56591 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#c56591 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Macro guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Define guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#36817e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#36817e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#36817e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#36817e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#778b81 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#778b81 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Ignore guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#778b81 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#566b60 guibg=#f9ebd0 guisp=NONE gui=bold cterm=bold
  hi markdownLinkText guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownUrl guifg=#758b00 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownListMarker guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownCode guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownId guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi markdownIdDeclaration guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule guifg=#c56591 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdListItem guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdInlineURL guifg=#cc8500 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdLink guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi mkdURL guifg=#758b00 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi mkdCode guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link mkdCodeDelimiter Delimiter
  hi mkdID guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule guifg=#c56591 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rstInterpretedTextOrHyperlinkReference guifg=#758b00 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi rstStandaloneHyperlink guifg=#758b00 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi! link rstTableLines Delimiter
  hi texBeginEndName guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi texDocTypeArgs guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlArg guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlTagName guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlEndTag guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi htmlLink guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link xmlTagName htmlTagName
  hi! link xmlAttrib htmlArg
  hi! link xmlEndTag htmlEndTag
  hi! link xmlEqual Operator
  hi cssClassName guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssClassNameDot guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssProp guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssAttr guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssFunctionName guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssTagName guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssPseudoClassId guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssPseudoClassFn guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi cssImportant guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi sassDefault guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassVariable guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassMixing guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassMixinName guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassClassChar guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassControl guifg=#c56591 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassInclude guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassAmpersand guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi sassClass guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssSelectorName guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssVariable guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssFunctionName guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssParameterList guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi scssDefault guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi lessVariable guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptFunction guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptGlobal guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaScriptNull guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link javaScriptParens Delimiter
  hi! link javaScriptBraces Delimiter
  hi jsThis guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsVariableDef guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsObjectProp guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsFunction guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsNull guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsPrototype guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsAsyncKeyword guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalObjects guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsGlobalNodeObjects guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsObjectMethodType guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi jsArrowFunction guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link jsExceptions Exception
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsSwitchBraces Delimiter
  hi! link jsRepeatBraces Delimiter
  hi! link jsIfElseBraces Delimiter
  hi typescriptStorageClass guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptLabel guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptGlobalObjects guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptGlobal guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi typescriptLogicSymbols guifg=#c56591 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons Delimiter
  hi dartClassDecl guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartInterpolation guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartAssert guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartTypedef guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartCoreClasses guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dartMetadata guifg=#c56591 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeSpecialVar guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeCurlies guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeInterp guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeInterpDelim guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeGlobal guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi coffeeObjAssign guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi purescriptConstructor guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptImport guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptImportAs guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptAsKeyword guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi purescriptImportKeyword guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaScopeDecl guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaAnnotation guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi javaStatement guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktStructure guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktStatement guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ktArrow guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonStatement guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonBuiltinFunc guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonDecorator guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi pythonDottedName guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPackage guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goImport guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goDeclaration guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goPredefinedIdentifiers guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi goLabel guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustExternCrate guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustSelf guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustFuncCall guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustStructure guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rustPubScopeCrate guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpUseClass guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpUseAlias guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClass guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClasses guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpClassExtends guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpVarSelector guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpFunction guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpMethod guifg=#5c7aa9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi phpMethodsVar guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi csUnspecifiedStatement guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csModifier guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csNewType guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csClassType guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi csContextualStatement guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi fsharpModifier guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpSymbol guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpTypeName guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpCoreClass guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpModule guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi fsharpOption guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link fsharpKeyChar Delimiter
  hi rubyModule guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyModuleName guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyClass guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyClassName guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyConstant guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyDefine guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi rubyPseudoVariable guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementPackage guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlPackageDecl guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementInclude guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementStorage guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlOperator guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementList guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlMethod guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlVarSimpleMemberName guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementScalar guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementNumeric guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi perlStatementHash guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi haskellDeclKeyword guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellDecl guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellParens guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellBrackets guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi haskellWhere guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaLocal guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaFuncKeyword guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaFuncCall guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaSpecialValue guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi luaSpecialTable guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi moonObject guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonObjAssign guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonDotAccess guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonInterpDelim guifg=#cc8500 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonInterp guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi moonLuaFunc guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dEnum guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dScopeDecl guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dStructure guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dOperator guifg=#2d8d4c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dAssert guifg=#d4576a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dAnnotation guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi dAttribute guifg=#758b00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi tomlTable guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StartifySection guifg=#d26e41 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEWarningSign guifg=#d26e41 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi ALEErrorSign guifg=#d4576a guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi ALEInfoSign guifg=#5c7aa9 guibg=#f6e2ba guisp=NONE gui=NONE cterm=NONE
  hi ALEError guifg=NONE guibg=#f6babd guisp=NONE gui=NONE cterm=NONE
  hi ALEWarning guifg=NONE guibg=#eecbb4 guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextError guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextWarning guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ALEVirtualTextInfo guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens guifg=#778b81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak guifg=NONE guibg=#c1e5b1 guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Todo gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
    hi htmlItalic gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'light_transp_bg', 0)
    hi Normal ctermfg=241 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=241 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=241 ctermbg=230 cterm=NONE
    hi Terminal ctermfg=241 ctermbg=230 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=230 cterm=NONE
  hi Conceal ctermfg=66 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=223 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=223 cterm=NONE
  hi CursorLineNr ctermfg=241 ctermbg=223 cterm=NONE
  hi LineNr ctermfg=66 ctermbg=223 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=223 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=151 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=152 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=217 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=223 cterm=NONE
  hi Directory ctermfg=29 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=66 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=173 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=67 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=30 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=66 ctermbg=223 cterm=NONE
  hi Folded ctermfg=66 ctermbg=223 cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=151 cterm=underline
  hi Search ctermfg=NONE ctermbg=151 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=66 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=241 ctermbg=223 cterm=NONE
  hi PmenuSel ctermfg=230 ctermbg=66 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=223 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=66 cterm=NONE
  hi Question ctermfg=29 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=167 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=173 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=67 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=168 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=230 ctermbg=66 cterm=NONE
  hi StatusLineNC ctermfg=241 ctermbg=223 cterm=NONE
  hi TabLine ctermfg=241 ctermbg=223 cterm=NONE
  hi TabLineFill ctermfg=241 ctermbg=223 cterm=NONE
  hi TabLineSel ctermfg=230 ctermbg=66 cterm=NONE
  hi VertSplit ctermfg=66 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=223 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=223 cterm=italic
  hi WildMenu ctermfg=230 ctermbg=241 cterm=NONE
  hi Todo ctermfg=168 ctermbg=NONE cterm=italic
  hi Conditional ctermfg=168 ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=168 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=167 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=167 ctermbg=NONE cterm=NONE
  hi Macro ctermfg=167 ctermbg=NONE cterm=NONE
  hi Define ctermfg=167 ctermbg=NONE cterm=NONE
  hi Title ctermfg=167 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=173 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=173 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=173 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=173 ctermbg=NONE cterm=NONE
  hi Type ctermfg=172 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=172 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=29 ctermbg=NONE cterm=NONE
  hi Function ctermfg=29 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=64 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=64 ctermbg=NONE cterm=NONE
  hi Special ctermfg=64 ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=64 ctermbg=NONE cterm=NONE
  hi String ctermfg=30 ctermbg=NONE cterm=NONE
  hi Character ctermfg=30 ctermbg=NONE cterm=NONE
  hi Number ctermfg=30 ctermbg=NONE cterm=NONE
  hi Float ctermfg=30 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=67 ctermbg=NONE cterm=NONE
  hi Label ctermfg=67 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=67 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=67 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=67 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=66 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=66 ctermbg=NONE cterm=italic
  hi Ignore ctermfg=66 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=66 cterm=NONE
  hi ToolbarButton ctermfg=241 ctermbg=230 cterm=bold
  hi markdownLinkText ctermfg=172 ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=64 ctermbg=NONE cterm=underline
  hi markdownListMarker ctermfg=67 ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=29 ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=173 ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=173 ctermbg=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule ctermfg=168 ctermbg=NONE cterm=NONE
  hi mkdListItem ctermfg=67 ctermbg=NONE cterm=NONE
  hi mkdInlineURL ctermfg=172 ctermbg=NONE cterm=underline
  hi mkdLink ctermfg=172 ctermbg=NONE cterm=NONE
  hi mkdURL ctermfg=64 ctermbg=NONE cterm=underline
  hi mkdCode ctermfg=29 ctermbg=NONE cterm=NONE
  hi! link mkdCodeDelimiter Delimiter
  hi mkdID ctermfg=173 ctermbg=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule ctermfg=168 ctermbg=NONE cterm=NONE
  hi rstInterpretedTextOrHyperlinkReference ctermfg=64 ctermbg=NONE cterm=underline
  hi rstStandaloneHyperlink ctermfg=64 ctermbg=NONE cterm=underline
  hi! link rstTableLines Delimiter
  hi texBeginEndName ctermfg=167 ctermbg=NONE cterm=NONE
  hi texDocTypeArgs ctermfg=29 ctermbg=NONE cterm=NONE
  hi htmlArg ctermfg=173 ctermbg=NONE cterm=NONE
  hi htmlTagName ctermfg=64 ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=172 ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link xmlTagName htmlTagName
  hi! link xmlAttrib htmlArg
  hi! link xmlEndTag htmlEndTag
  hi! link xmlEqual Operator
  hi cssClassName ctermfg=173 ctermbg=NONE cterm=NONE
  hi cssClassNameDot ctermfg=172 ctermbg=NONE cterm=NONE
  hi cssProp ctermfg=64 ctermbg=NONE cterm=NONE
  hi cssAttr ctermfg=29 ctermbg=NONE cterm=NONE
  hi cssFunctionName ctermfg=172 ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=167 ctermbg=NONE cterm=NONE
  hi cssPseudoClassId ctermfg=67 ctermbg=NONE cterm=NONE
  hi cssPseudoClassFn ctermfg=67 ctermbg=NONE cterm=NONE
  hi cssImportant ctermfg=167 ctermbg=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi sassDefault ctermfg=167 ctermbg=NONE cterm=NONE
  hi sassVariable ctermfg=29 ctermbg=NONE cterm=NONE
  hi sassMixing ctermfg=173 ctermbg=NONE cterm=NONE
  hi sassMixinName ctermfg=29 ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=173 ctermbg=NONE cterm=NONE
  hi sassControl ctermfg=168 ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=167 ctermbg=NONE cterm=NONE
  hi sassAmpersand ctermfg=167 ctermbg=NONE cterm=NONE
  hi sassClass ctermfg=173 ctermbg=NONE cterm=NONE
  hi scssSelectorName ctermfg=173 ctermbg=NONE cterm=NONE
  hi scssVariable ctermfg=29 ctermbg=NONE cterm=NONE
  hi scssFunctionName ctermfg=172 ctermbg=NONE cterm=NONE
  hi scssParameterList ctermfg=29 ctermbg=NONE cterm=NONE
  hi scssDefault ctermfg=167 ctermbg=NONE cterm=NONE
  hi lessVariable ctermfg=172 ctermbg=NONE cterm=NONE
  hi javaScriptFunction ctermfg=173 ctermbg=NONE cterm=NONE
  hi javaScriptGlobal ctermfg=172 ctermbg=NONE cterm=NONE
  hi javaScriptNull ctermfg=172 ctermbg=NONE cterm=NONE
  hi! link javaScriptParens Delimiter
  hi! link javaScriptBraces Delimiter
  hi jsThis ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsVariableDef ctermfg=64 ctermbg=NONE cterm=NONE
  hi jsObjectProp ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=173 ctermbg=NONE cterm=NONE
  hi jsNull ctermfg=172 ctermbg=NONE cterm=NONE
  hi jsPrototype ctermfg=173 ctermbg=NONE cterm=NONE
  hi jsAsyncKeyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=167 ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=167 ctermbg=NONE cterm=NONE
  hi jsObjectMethodType ctermfg=173 ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=173 ctermbg=NONE cterm=NONE
  hi! link jsExceptions Exception
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsSwitchBraces Delimiter
  hi! link jsRepeatBraces Delimiter
  hi! link jsIfElseBraces Delimiter
  hi typescriptStorageClass ctermfg=167 ctermbg=NONE cterm=NONE
  hi typescriptLabel ctermfg=167 ctermbg=NONE cterm=NONE
  hi typescriptGlobalObjects ctermfg=167 ctermbg=NONE cterm=NONE
  hi typescriptGlobal ctermfg=172 ctermbg=NONE cterm=NONE
  hi typescriptLogicSymbols ctermfg=168 ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons Delimiter
  hi dartClassDecl ctermfg=167 ctermbg=NONE cterm=NONE
  hi dartInterpolation ctermfg=64 ctermbg=NONE cterm=NONE
  hi dartAssert ctermfg=172 ctermbg=NONE cterm=NONE
  hi dartTypedef ctermfg=173 ctermbg=NONE cterm=NONE
  hi dartCoreClasses ctermfg=167 ctermbg=NONE cterm=NONE
  hi dartMetadata ctermfg=168 ctermbg=NONE cterm=NONE
  hi coffeeSpecialVar ctermfg=172 ctermbg=NONE cterm=NONE
  hi coffeeCurlies ctermfg=29 ctermbg=NONE cterm=NONE
  hi coffeeInterp ctermfg=64 ctermbg=NONE cterm=NONE
  hi coffeeInterpDelim ctermfg=172 ctermbg=NONE cterm=NONE
  hi coffeeGlobal ctermfg=167 ctermbg=NONE cterm=NONE
  hi coffeeObjAssign ctermfg=29 ctermbg=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi purescriptConstructor ctermfg=167 ctermbg=NONE cterm=NONE
  hi purescriptImport ctermfg=29 ctermbg=NONE cterm=NONE
  hi purescriptImportAs ctermfg=173 ctermbg=NONE cterm=NONE
  hi purescriptAsKeyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi purescriptImportKeyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaScopeDecl ctermfg=167 ctermbg=NONE cterm=NONE
  hi javaAnnotation ctermfg=172 ctermbg=NONE cterm=NONE
  hi javaStatement ctermfg=29 ctermbg=NONE cterm=NONE
  hi ktStructure ctermfg=167 ctermbg=NONE cterm=NONE
  hi ktStatement ctermfg=29 ctermbg=NONE cterm=NONE
  hi ktArrow ctermfg=67 ctermbg=NONE cterm=NONE
  hi pythonStatement ctermfg=173 ctermbg=NONE cterm=NONE
  hi pythonBuiltinFunc ctermfg=67 ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=173 ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=167 ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=167 ctermbg=NONE cterm=NONE
  hi goImport ctermfg=167 ctermbg=NONE cterm=NONE
  hi goDeclaration ctermfg=167 ctermbg=NONE cterm=NONE
  hi goPredefinedIdentifiers ctermfg=29 ctermbg=NONE cterm=NONE
  hi goLabel ctermfg=173 ctermbg=NONE cterm=NONE
  hi rustExternCrate ctermfg=172 ctermbg=NONE cterm=NONE
  hi rustSelf ctermfg=172 ctermbg=NONE cterm=NONE
  hi rustFuncCall ctermfg=64 ctermbg=NONE cterm=NONE
  hi rustStructure ctermfg=67 ctermbg=NONE cterm=NONE
  hi rustPubScopeCrate ctermfg=29 ctermbg=NONE cterm=NONE
  hi phpUseClass ctermfg=29 ctermbg=NONE cterm=NONE
  hi phpUseAlias ctermfg=172 ctermbg=NONE cterm=NONE
  hi phpClass ctermfg=29 ctermbg=NONE cterm=NONE
  hi phpClasses ctermfg=167 ctermbg=NONE cterm=NONE
  hi phpClassExtends ctermfg=172 ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=29 ctermbg=NONE cterm=NONE
  hi phpFunction ctermfg=29 ctermbg=NONE cterm=NONE
  hi phpMethod ctermfg=67 ctermbg=NONE cterm=NONE
  hi phpMethodsVar ctermfg=29 ctermbg=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi csUnspecifiedStatement ctermfg=167 ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=167 ctermbg=NONE cterm=NONE
  hi csNewType ctermfg=64 ctermbg=NONE cterm=NONE
  hi csClassType ctermfg=29 ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=173 ctermbg=NONE cterm=NONE
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi fsharpModifier ctermfg=167 ctermbg=NONE cterm=NONE
  hi fsharpSymbol ctermfg=64 ctermbg=NONE cterm=NONE
  hi fsharpTypeName ctermfg=29 ctermbg=NONE cterm=NONE
  hi fsharpCoreClass ctermfg=167 ctermbg=NONE cterm=NONE
  hi fsharpModule ctermfg=29 ctermbg=NONE cterm=NONE
  hi fsharpOption ctermfg=167 ctermbg=NONE cterm=NONE
  hi! link fsharpKeyChar Delimiter
  hi rubyModule ctermfg=167 ctermbg=NONE cterm=NONE
  hi rubyModuleName ctermfg=172 ctermbg=NONE cterm=NONE
  hi rubyClass ctermfg=173 ctermbg=NONE cterm=NONE
  hi rubyClassName ctermfg=29 ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=64 ctermbg=NONE cterm=NONE
  hi rubyDefine ctermfg=173 ctermbg=NONE cterm=NONE
  hi rubyPseudoVariable ctermfg=172 ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=167 ctermbg=NONE cterm=NONE
  hi perlPackageDecl ctermfg=29 ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=167 ctermbg=NONE cterm=NONE
  hi perlStatementStorage ctermfg=167 ctermbg=NONE cterm=NONE
  hi perlOperator ctermfg=173 ctermbg=NONE cterm=NONE
  hi perlStatementList ctermfg=29 ctermbg=NONE cterm=NONE
  hi perlMethod ctermfg=172 ctermbg=NONE cterm=NONE
  hi perlVarSimpleMemberName ctermfg=29 ctermbg=NONE cterm=NONE
  hi perlStatementScalar ctermfg=29 ctermbg=NONE cterm=NONE
  hi perlStatementNumeric ctermfg=29 ctermbg=NONE cterm=NONE
  hi perlStatementHash ctermfg=167 ctermbg=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi haskellDeclKeyword ctermfg=167 ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=173 ctermbg=NONE cterm=NONE
  hi haskellParens ctermfg=29 ctermbg=NONE cterm=NONE
  hi haskellBrackets ctermfg=29 ctermbg=NONE cterm=NONE
  hi haskellWhere ctermfg=167 ctermbg=NONE cterm=NONE
  hi luaLocal ctermfg=167 ctermbg=NONE cterm=NONE
  hi luaFuncKeyword ctermfg=173 ctermbg=NONE cterm=NONE
  hi luaFuncCall ctermfg=64 ctermbg=NONE cterm=NONE
  hi luaSpecialValue ctermfg=172 ctermbg=NONE cterm=NONE
  hi luaSpecialTable ctermfg=172 ctermbg=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi moonObject ctermfg=167 ctermbg=NONE cterm=NONE
  hi moonObjAssign ctermfg=64 ctermbg=NONE cterm=NONE
  hi moonDotAccess ctermfg=172 ctermbg=NONE cterm=NONE
  hi moonInterpDelim ctermfg=172 ctermbg=NONE cterm=NONE
  hi moonInterp ctermfg=64 ctermbg=NONE cterm=NONE
  hi moonLuaFunc ctermfg=29 ctermbg=NONE cterm=NONE
  hi dEnum ctermfg=173 ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=167 ctermbg=NONE cterm=NONE
  hi dStructure ctermfg=167 ctermbg=NONE cterm=NONE
  hi dOperator ctermfg=29 ctermbg=NONE cterm=NONE
  hi dAssert ctermfg=167 ctermbg=NONE cterm=NONE
  hi dAnnotation ctermfg=173 ctermbg=NONE cterm=NONE
  hi dAttribute ctermfg=64 ctermbg=NONE cterm=NONE
  hi tomlTable ctermfg=173 ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=173 ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=173 ctermbg=223 cterm=NONE
  hi ALEErrorSign ctermfg=167 ctermbg=223 cterm=NONE
  hi ALEInfoSign ctermfg=67 ctermbg=223 cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=217 cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=223 cterm=NONE
  hi ALEVirtualTextError ctermfg=66 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=66 ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=66 ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=66 ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=151 cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'light_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi Terminal ctermfg=Black ctermbg=White cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=White cterm=NONE
  hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi LineNr ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=LightGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=LightBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=Blue ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=LightGrey cterm=NONE
  hi IncSearch ctermfg=NONE ctermbg=LightGreen cterm=underline
  hi Search ctermfg=NONE ctermbg=LightGreen cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Grey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Grey cterm=NONE
  hi Question ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=White ctermbg=Grey cterm=NONE
  hi StatusLineNC ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Grey cterm=NONE
  hi VertSplit ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=LightGrey cterm=italic
  hi WildMenu ctermfg=White ctermbg=Black cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=italic
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Repeat ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Red ctermbg=NONE cterm=NONE
  hi Macro ctermfg=Red ctermbg=NONE cterm=NONE
  hi Define ctermfg=Red ctermbg=NONE cterm=NONE
  hi Title ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Structure ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Green ctermbg=NONE cterm=NONE
  hi Function ctermfg=Green ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Special ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Boolean ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi String ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Character ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Number ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Float ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Label ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Grey ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Grey ctermbg=NONE cterm=italic
  hi Ignore ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Grey cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=White cterm=bold
  hi markdownLinkText ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi markdownUrl ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi markdownListMarker ctermfg=Blue ctermbg=NONE cterm=NONE
  hi markdownCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi markdownId ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi markdownIdDeclaration ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link markdownBoldDelimiter Comment
  hi! link markdownItalicDelimiter Comment
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownRule ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi mkdListItem ctermfg=Blue ctermbg=NONE cterm=NONE
  hi mkdInlineURL ctermfg=LightGrey ctermbg=NONE cterm=underline
  hi mkdLink ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi mkdURL ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi mkdCode ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link mkdCodeDelimiter Delimiter
  hi mkdID ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link mkdBold Comment
  hi! link mkdItalic Comment
  hi mkdRule ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi rstInterpretedTextOrHyperlinkReference ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi rstStandaloneHyperlink ctermfg=LightGreen ctermbg=NONE cterm=underline
  hi! link rstTableLines Delimiter
  hi texBeginEndName ctermfg=Red ctermbg=NONE cterm=NONE
  hi texDocTypeArgs ctermfg=Green ctermbg=NONE cterm=NONE
  hi htmlArg ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi htmlTagName ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi htmlLink ctermfg=NONE ctermbg=NONE cterm=underline
  hi htmlBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi htmlItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link xmlTagName htmlTagName
  hi! link xmlAttrib htmlArg
  hi! link xmlEndTag htmlEndTag
  hi! link xmlEqual Operator
  hi cssClassName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi cssClassNameDot ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi cssProp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi cssAttr ctermfg=Green ctermbg=NONE cterm=NONE
  hi cssFunctionName ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi cssTagName ctermfg=Red ctermbg=NONE cterm=NONE
  hi cssPseudoClassId ctermfg=Blue ctermbg=NONE cterm=NONE
  hi cssPseudoClassFn ctermfg=Blue ctermbg=NONE cterm=NONE
  hi cssImportant ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link cssBraces Delimiter
  hi! link cssSelectorOp Delimiter
  hi! link cssSelectorOp2 Delimiter
  hi sassDefault ctermfg=Red ctermbg=NONE cterm=NONE
  hi sassVariable ctermfg=Green ctermbg=NONE cterm=NONE
  hi sassMixing ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi sassMixinName ctermfg=Green ctermbg=NONE cterm=NONE
  hi sassClassChar ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi sassControl ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi sassInclude ctermfg=Red ctermbg=NONE cterm=NONE
  hi sassAmpersand ctermfg=Red ctermbg=NONE cterm=NONE
  hi sassClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi scssSelectorName ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi scssVariable ctermfg=Green ctermbg=NONE cterm=NONE
  hi scssFunctionName ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi scssParameterList ctermfg=Green ctermbg=NONE cterm=NONE
  hi scssDefault ctermfg=Red ctermbg=NONE cterm=NONE
  hi lessVariable ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaScriptFunction ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi javaScriptGlobal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaScriptNull ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi! link javaScriptParens Delimiter
  hi! link javaScriptBraces Delimiter
  hi jsThis ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi jsVariableDef ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi jsObjectProp ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi jsFunction ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsNull ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi jsPrototype ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsAsyncKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi jsGlobalObjects ctermfg=Red ctermbg=NONE cterm=NONE
  hi jsGlobalNodeObjects ctermfg=Red ctermbg=NONE cterm=NONE
  hi jsObjectMethodType ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi jsArrowFunction ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link jsExceptions Exception
  hi! link jsParens Delimiter
  hi! link jsBraces Delimiter
  hi! link jsBrackets Delimiter
  hi! link jsFuncBraces Delimiter
  hi! link jsFuncParens Delimiter
  hi! link jsObjectBraces Delimiter
  hi! link jsObjectParens Delimiter
  hi! link jsSwitchBraces Delimiter
  hi! link jsRepeatBraces Delimiter
  hi! link jsIfElseBraces Delimiter
  hi typescriptStorageClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi typescriptLabel ctermfg=Red ctermbg=NONE cterm=NONE
  hi typescriptGlobalObjects ctermfg=Red ctermbg=NONE cterm=NONE
  hi typescriptGlobal ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi typescriptLogicSymbols ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi! link typescriptExceptions Exception
  hi! link typescriptParens Delimiter
  hi! link typescriptBraces Delimiter
  hi! link typescriptEndColons Delimiter
  hi dartClassDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi dartInterpolation ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi dartAssert ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi dartTypedef ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dartCoreClasses ctermfg=Red ctermbg=NONE cterm=NONE
  hi dartMetadata ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi coffeeSpecialVar ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi coffeeCurlies ctermfg=Green ctermbg=NONE cterm=NONE
  hi coffeeInterp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi coffeeInterpDelim ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi coffeeGlobal ctermfg=Red ctermbg=NONE cterm=NONE
  hi coffeeObjAssign ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link coffeeParen Delimiter
  hi! link coffeeCurly Delimiter
  hi! link coffeeBracket Delimiter
  hi purescriptConstructor ctermfg=Red ctermbg=NONE cterm=NONE
  hi purescriptImport ctermfg=Green ctermbg=NONE cterm=NONE
  hi purescriptImportAs ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi purescriptAsKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi purescriptImportKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link javaParen Delimiter
  hi javaScopeDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi javaAnnotation ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi javaStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi ktStructure ctermfg=Red ctermbg=NONE cterm=NONE
  hi ktStatement ctermfg=Green ctermbg=NONE cterm=NONE
  hi ktArrow ctermfg=Blue ctermbg=NONE cterm=NONE
  hi pythonStatement ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonBuiltinFunc ctermfg=Blue ctermbg=NONE cterm=NONE
  hi pythonDecorator ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi pythonDottedName ctermfg=Red ctermbg=NONE cterm=NONE
  hi goPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi goImport ctermfg=Red ctermbg=NONE cterm=NONE
  hi goDeclaration ctermfg=Red ctermbg=NONE cterm=NONE
  hi goPredefinedIdentifiers ctermfg=Green ctermbg=NONE cterm=NONE
  hi goLabel ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rustExternCrate ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi rustSelf ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi rustFuncCall ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi rustStructure ctermfg=Blue ctermbg=NONE cterm=NONE
  hi rustPubScopeCrate ctermfg=Green ctermbg=NONE cterm=NONE
  hi phpUseClass ctermfg=Green ctermbg=NONE cterm=NONE
  hi phpUseAlias ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi phpClass ctermfg=Green ctermbg=NONE cterm=NONE
  hi phpClasses ctermfg=Red ctermbg=NONE cterm=NONE
  hi phpClassExtends ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi phpVarSelector ctermfg=Green ctermbg=NONE cterm=NONE
  hi phpFunction ctermfg=Green ctermbg=NONE cterm=NONE
  hi phpMethod ctermfg=Blue ctermbg=NONE cterm=NONE
  hi phpMethodsVar ctermfg=Green ctermbg=NONE cterm=NONE
  hi! link phpMemberSelector Delimiter
  hi csUnspecifiedStatement ctermfg=Red ctermbg=NONE cterm=NONE
  hi csModifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi csNewType ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi csClassType ctermfg=Green ctermbg=NONE cterm=NONE
  hi csContextualStatement ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi! link csBraces Delimiter
  hi! link csParens Delimiter
  hi fsharpModifier ctermfg=Red ctermbg=NONE cterm=NONE
  hi fsharpSymbol ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi fsharpTypeName ctermfg=Green ctermbg=NONE cterm=NONE
  hi fsharpCoreClass ctermfg=Red ctermbg=NONE cterm=NONE
  hi fsharpModule ctermfg=Green ctermbg=NONE cterm=NONE
  hi fsharpOption ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link fsharpKeyChar Delimiter
  hi rubyModule ctermfg=Red ctermbg=NONE cterm=NONE
  hi rubyModuleName ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi rubyClass ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rubyClassName ctermfg=Green ctermbg=NONE cterm=NONE
  hi rubyConstant ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi rubyDefine ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi rubyPseudoVariable ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi perlStatementPackage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlPackageDecl ctermfg=Green ctermbg=NONE cterm=NONE
  hi perlStatementInclude ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlStatementStorage ctermfg=Red ctermbg=NONE cterm=NONE
  hi perlOperator ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi perlStatementList ctermfg=Green ctermbg=NONE cterm=NONE
  hi perlMethod ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi perlVarSimpleMemberName ctermfg=Green ctermbg=NONE cterm=NONE
  hi perlStatementScalar ctermfg=Green ctermbg=NONE cterm=NONE
  hi perlStatementNumeric ctermfg=Green ctermbg=NONE cterm=NONE
  hi perlStatementHash ctermfg=Red ctermbg=NONE cterm=NONE
  hi! link perlStringStartEnd Delimiter
  hi haskellDeclKeyword ctermfg=Red ctermbg=NONE cterm=NONE
  hi haskellDecl ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi haskellParens ctermfg=Green ctermbg=NONE cterm=NONE
  hi haskellBrackets ctermfg=Green ctermbg=NONE cterm=NONE
  hi haskellWhere ctermfg=Red ctermbg=NONE cterm=NONE
  hi luaLocal ctermfg=Red ctermbg=NONE cterm=NONE
  hi luaFuncKeyword ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi luaFuncCall ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi luaSpecialValue ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi luaSpecialTable ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi! link luaBraces Delimiter
  hi moonObject ctermfg=Red ctermbg=NONE cterm=NONE
  hi moonObjAssign ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi moonDotAccess ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi moonInterpDelim ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi moonInterp ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi moonLuaFunc ctermfg=Green ctermbg=NONE cterm=NONE
  hi dEnum ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dScopeDecl ctermfg=Red ctermbg=NONE cterm=NONE
  hi dStructure ctermfg=Red ctermbg=NONE cterm=NONE
  hi dOperator ctermfg=Green ctermbg=NONE cterm=NONE
  hi dAssert ctermfg=Red ctermbg=NONE cterm=NONE
  hi dAnnotation ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi dAttribute ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi tomlTable ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi StartifySection ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ALEWarningSign ctermfg=Yellow ctermbg=LightGrey cterm=NONE
  hi ALEErrorSign ctermfg=Red ctermbg=LightGrey cterm=NONE
  hi ALEInfoSign ctermfg=Blue ctermbg=LightGrey cterm=NONE
  hi ALEError ctermfg=NONE ctermbg=LightRed cterm=NONE
  hi ALEWarning ctermfg=NONE ctermbg=LightYellow cterm=NONE
  hi ALEVirtualTextError ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextWarning ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ALEVirtualTextInfo ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link ALEVirtualTextStyleError ALEVirtualTextError
  hi! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
  hi CocHighlightText ctermfg=NONE ctermbg=NONE cterm=bold
  hi CocCodeLens ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link CocErrorSign ALEErrorSign
  hi! link CocWarningSign ALEWarningSign
  hi! link CocInfoSign ALEInfoSign
  hi! link CocHintSign Label
  hi! link CocErrorHighlight ALEError
  hi! link CocWarningHighlight ALEWarning
  hi! link CocInfoHighlight ALEInfo
  hi! link CocWarningVirtualText ALEVirtualTextWarning
  hi! link CocErrorVirtualText ALEVirtualTextError
  hi! link CocInfoVirtualText ALEVirtualTextInfo
  hi! link CocHintVirtualText ALEVirtualTextInfo
  hi! link CocCodeLens ALEVirtualTextInfo
  hi MatchParenCur ctermfg=NONE ctermbg=NONE cterm=bold
  hi MatchWord ctermfg=NONE ctermbg=NONE cterm=underline
  hi MatchWordCur ctermfg=NONE ctermbg=NONE cterm=underline
  hi Sneak ctermfg=NONE ctermbg=LightGreen cterm=NONE
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Todo cterm=NONE
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
    hi markdownItalic cterm=NONE
    hi htmlItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: light         #f9ebd0           ~                 White
" Color: lightgrey     #f6e2ba           ~                 LightGrey
" Color: grey          #778b81           ~                 Grey
" Color: dark          #566b60           ~                 Black
" Color: red           #d4576a           ~                 Red
" Color: orange        #d26e41           ~                 Yellow
" Color: yellow        #cc8500           ~                 LightGrey
" Color: lemon         #758b00           ~                 LightGreen
" Color: green         #2d8d4c           ~                 Green
" Color: cyan          #36817e           ~                 Cyan
" Color: blue          #5c7aa9           ~                 Blue
" Color: magenta       #c56591           ~                 Magenta
" Color: lightred      #f6babd           ~                 LightRed
" Color: lightgreen    #c1e5b1           ~                 LightGreen
" Color: lightorange   #eecbb4           ~                 LightYellow
" Color: lightblue     #bae1f0           ~                 LightBlue
" Term colors: dark red green yellow blue magenta cyan light
" Term colors: dark red green yellow
" Term colors: blue magenta cyan light
" Color: unused #000000 0 0
